image: jangrewe/gitlab-ci-android

variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_BUILD_TOOLS: "29.0.2"
  ANDROID_SDK_TOOLS:   "4333796"
  PROJECT_NAME: bee
  PROJECT_VERSION: 1.0.3
#before_script:
#  - apt-get --quiet update --yes
#  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
#  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
#  - unzip -d android-sdk-linux android-sdk.zip
#  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
#  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
#  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
#  - export ANDROID_HOME=$PWD/android-sdk-linux
#  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
#  - chmod +x ./gradlew
#  # temporarily disable checking for EPIPE error and use yes to accept all licenses
#  - set +o pipefail
#  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
#  - set -o pipefail

stages:
  - build
  - test
  - release

lintDebug:
  stage: build
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

debugTests:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testDebug
assembleRelease:
  stage: release
  only:
    - master
  script:
    - base64 -d $KEYSTORE_FILE > my.keystore
    - ./gradlew assembleRelease
      -Pandroid.injected.signing.store.file=$(pwd)/my.keystore
      -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD
      -Pandroid.injected.signing.key.alias=$KEY_ALIAS
      -Pandroid.injected.signing.key.password=$KEY_PASSWORD
    - mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/$PROJECT_NAME-$PROJECT_VERSION-$CI_JOB_ID.apk
    - git log --oneline --decorate > CHANGELOG
    - git tag -a $PROJECT_NAME-$PROJECT_VERSION-$CI_JOB_ID -F CHANGELOG
  artifacts:
    paths:
      - app/build/outputs/apk/release
      - CHANGELOG
